version: '2'
services:
     ruby-v2:
          restart: unless-stopped
          image: 'ghcr.io/ruby-network/ruby-v2:main'
          ports:
               - <your port here>:8080   
          #ADVANCED ITEMS BELOW
          #     - ${PORT}:8080
          #env_file:
          #     - .env.docker  
          #environment:
          #     - URL=${URL}
#networks:
#  default:
#    external:
#      name: default_net
