[build]
builder = "DOCKERFILE"
buildCommand = "docker build --no-cache "
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker-compose up -d"
healthcheckPath = "/"
restartPolicyType = "NEVER"
healthcheckTimeout = 100
