services:
    - type: web
      name: ruby
      env: node
      plan: free
      buildCommand: yarn && yarn build
      startCommand: yarn start
      envVars:
        - key: PORT
          value: 80
        - key: CPUS
          value: 0
